# Generated by Django 5.2.8 on 2025-11-27 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Denúncia')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('tipo', models.CharField(choices=[('vazamento', 'Vazamento de Dados'), ('uso_indevido', 'Uso Indevido de Dados'), ('acesso_nao_autorizado', 'Acesso Não Autorizado'), ('coleta_excessiva', 'Coleta Excessiva de Dados'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de Violação')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para Contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('resolvida', 'Resolvida'), ('arquivada', 'Arquivada')], default='pendente', max_length=20)),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observações Internas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('denunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
