# Generated by Django 5.2.8 on 2025-11-27 02:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='token_acompanhamento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
